package CollectionsTask.classification;

public enum GemPreciousness {
    PRECIOUS_FIRST_CLASS, PRECIOUS_SECOND_CLASS, PRECIOUS_THIRD_CLASS, SEMI_PRECIOUS_FIRST_CLASS,
    SEMI_PRECIOUS_SECOND_CLASS, SEMI_PRECIOUS_THIRD_CLASS, ORGANOGENIC
}
